// This file is generated by `flutterfire configure`.
// Run the following command to regenerate it with your Firebase project:
//
//   flutterfire configure
//
// See setup instructions in SETUP.md

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvPl_cQqAX3eZH5lMvwRzEQPUxdoFtSj8',
    appId: '1:512356153988:web:af97caf654226d9e4660d1',
    messagingSenderId: '512356153988',
    projectId: 'asinux-89da0',
    authDomain: 'asinux-89da0.firebaseapp.com',
    databaseURL: 'https://asinux-89da0-default-rtdb.firebaseio.com',
    storageBucket: 'asinux-89da0.firebasestorage.app',
    measurementId: 'G-6MBDL2081K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz26w1PuSFz6N0Z0zhbgVL0vUNNE1xteM',
    appId: '1:512356153988:android:e369672ca84329784660d1',
    messagingSenderId: '512356153988',
    projectId: 'asinux-89da0',
    databaseURL: 'https://asinux-89da0-default-rtdb.firebaseio.com',
    storageBucket: 'asinux-89da0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4iFs5pb78uSeNnqyw4q8KhBST6eY67x8',
    appId: '1:512356153988:ios:cf1934ab8f4d9d6b4660d1',
    messagingSenderId: '512356153988',
    projectId: 'asinux-89da0',
    databaseURL: 'https://asinux-89da0-default-rtdb.firebaseio.com',
    storageBucket: 'asinux-89da0.firebasestorage.app',
    iosBundleId: 'com.asinux.asinuxapp',
  );

}